Bug fixed: #349.
PodcastGenerator/PodcastGenerator pull request #374
Opened 2020-12-09 20:32 UTC by StoryHack

Replaces 'Edit / Delete' link in admin navbar with a 'View All Episodes' link to a new page (admin/episodes_list.php) that shows all episodes, even the future ones, ordered by decending date, as most users will want to edit upcoming and recently published, so they shouldn't need to scroll.

* [x] I am the author of this code or the code is public domain
* [x] I release this code into the public domain

2020-12-09 20:44 UTC, StoryHack commented
This is particularly bothersome, as if you change the publication date, then PG doesn't know how to save the new xml file and rename the mp3.

This is one of the dangers of storing the publication date as part of the filename, rather than as a field in the xml.

2020-12-10 13:53 UTC, coldacid approved these changes
I haven't tried this but it looks good after eyeballing the code.

2021-01-29 09:39 UTC, emilengler requested changes
This is useful thanks! However I think it's better to not re-invent the wheel extend the getEpisodes function with an argument to ignore the timestamp of files.

2022-03-03 02:55 UTC, coldacid requested changes

2022-03-03 02:55 UTC, coldacid commented on PodcastGenerator/admin/episodes_list.php
> +function getEpisodeArray(){
Per https://github.com/PodcastGenerator/PodcastGenerator/pull/374#pullrequestreview-579086708 could you update the original `getEpisodes()` function and make use of it here? Thanks.

2022-03-03 02:55 UTC, coldacid commented on PodcastGenerator/admin/episodes_list.php
> +    <title><?php echo htmlspecialchars($config['podcast_title']); ?> - <?php echo _('Theme Buttons'); ?></title>
Probably should not be "Theme Buttons"

2022-03-04 04:30 UTC, merged