[WiP] Feature : better cover filename handling
PodcastGenerator/PodcastGenerator pull request #396
Opened 2021-01-23 17:41 UTC by Go-rom

* [x] I am the author of this code or the code is public domain
* [x] I release this code into the public domain

Hello,
first you have to know that this PR is my first "real" fix. I'm not a dev, so far my PR were mainly text fixes and translations on several projects.
I recently read https://github.com/PodcastGenerator/PodcastGenerator/issues/338 and this issue is also bothering me (can't change cover with Spotify Podcasts), so this PR aims to fix it.

**PR details**

When a new cover is uploaded, the original filename is kept as the new podcast name instead of the static name "itunes_image.jpg"
Also at first setup of Podcast Generator, config.php now generates a new variable : 'podcast_cover' with "itunes_image.jpg' as first value. When a new cover will be uploaded, the filename will be stored in this variable.

In case of a new episode which doesn't embed a cover art, it will displays the global podcast cover.

**This PR doesn't provide**
- Filename editing with a basic textfield, it only uses file selector.
- Multiple covers for episodes and seasons. It's a good feature request but needs a specific PR

**It may lack**
- Some failsafe code in order to prevent unwanted filenames
- Some code to support PG upgrades

The branch has been tested with a fresh install and it works.

Again, i'm not a dev so please give a deep look at this changes and provide me feedbacks, it's a good way for me to experience "easy hacks"

Task list :
- [ ] Fixes/improves based on feedbacks
- [ ] re-run a test with a fresh install
- [ ] wait for test results from other users
- [ ] mark this PR as ready to be merged

2021-01-28 21:11 UTC, Go-rom commented
I would like to go further about the upload feature.

Here are some thoughts : 

- Add PNG support (Global podcast requirements say that JPG and PNG are commonly accepted)
- Set min resolution and max resolution in pixels (Global podcast requirements start from 1400px to 3000 px)
- Check pixel density (Global podcast requirement : 72 dpi)
- Check if the file 
- Check filesize, must no be 0. I don't think that setting a max size is relevant
- Limit range of characters (a-z, 0-9; "-", "_") and enforce lowercase letters
- Check number of characters (i would say max. 20)
- Check if filename already exists (if user keeps the same filename, new cover art won't be detected by some podcast platform like Spotify)

Here are iTunes podcast requirements : https://help.apple.com/itc/podcasts_connect/#/itcb54353390

Tell me what you think about these suggestions, thank you

2021-01-29 11:23 UTC, emilengler commented
Thanks for working on this! We have already support for episode specific covers! I am just not sure if it was already included in 3.1 though

2021-01-29 11:55 UTC, Go-rom commented
> We have already support for episode specific covers! 

Yes but this PR is only about Podcast cover art. Currently, the artwork is saved as "itunes_image.jpg" and this choice is hard-coded. I checked your current master branch and didn't see anything about that.

This is related to https://github.com/PodcastGenerator/PodcastGenerator/issues/338
If you're already tackled this issue, let me know and i will close this PR. Thanks !

2022-03-03 03:05 UTC, coldacid requested changes

2022-03-03 03:05 UTC, coldacid commented on PodcastGenerator/themes/default/singleepisode.php
> +// If no episode cover art, we use the global feed covert art
Typo: "covert" -> "cover"

2022-03-03 03:05 UTC, coldacid commented on PodcastGenerator/core/backwards.php
> +\$podcast_cover = \"".$config['podcast_cover']."\";
Check to see if `$config['podcast_cover']` has a value, and write out itunes_image.jpg if it doesn't:

```php
\$podcast_cover = \"".(isset($config['podcast_cover']) ? $config['podcast_cover'] : 'itunes_image.jpg')."\";
```

2022-03-04 04:40 UTC, merged